# Generated by Django 4.0 on 2022-01-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='imagem',
            field=models.ImageField(default='imagens/None/no-img.jpg', upload_to='imagens/', verbose_name='Imagem Crachá'),
        ),
    ]
